"""update attend and meeting model

Revision ID: 5e02a63f5a26
Revises: fa18e1a40592
Create Date: 2025-08-31 22:57:26.647588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e02a63f5a26'
down_revision: Union[str, Sequence[str], None] = 'fa18e1a40592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('attended_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('meeting', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'is_active')
    op.drop_column('attendance', 'attended_at')
    # ### end Alembic commands ###
